import { PERMISSIONS } from './permissions';

/**
 * Role definitions
 * Backend uses ownership model (is_owner flag), not traditional roles
 * Frontend derives capabilities from ownership context
 */

export const ROLES = {
  OWNER: 'owner',
  VIEWER: 'viewer',
  AUTHENTICATED: 'authenticated',
  ANONYMOUS: 'anonymous',
};

/**
 * Role to permissions mapping
 * Defines what each role can do
 */
export const ROLE_PERMISSIONS = {
  [ROLES.OWNER]: [
    // Portfolio owners can do everything with their portfolio
    PERMISSIONS.PORTFOLIO_VIEW,
    PERMISSIONS.PORTFOLIO_EDIT,
    PERMISSIONS.PORTFOLIO_DELETE,
    PERMISSIONS.PORTFOLIO_PUBLISH,
    PERMISSIONS.PROJECT_CREATE,
    PERMISSIONS.PROJECT_VIEW,
    PERMISSIONS.PROJECT_EDIT,
    PERMISSIONS.PROJECT_DELETE,
    PERMISSIONS.SKILL_CREATE,
    PERMISSIONS.SKILL_VIEW,
    PERMISSIONS.SKILL_EDIT,
    PERMISSIONS.SKILL_DELETE,
    PERMISSIONS.EDUCATION_CREATE,
    PERMISSIONS.EDUCATION_VIEW,
    PERMISSIONS.EDUCATION_EDIT,
    PERMISSIONS.EDUCATION_DELETE,
    PERMISSIONS.SOCIAL_LINK_CREATE,
    PERMISSIONS.SOCIAL_LINK_VIEW,
    PERMISSIONS.SOCIAL_LINK_EDIT,
    PERMISSIONS.SOCIAL_LINK_DELETE,
    PERMISSIONS.DOCUMENT_UPLOAD,
    PERMISSIONS.DOCUMENT_VIEW,
    PERMISSIONS.DOCUMENT_DELETE,
    PERMISSIONS.VERSION_CREATE,
    PERMISSIONS.VERSION_VIEW,
    PERMISSIONS.VERSION_REVERT,
    PERMISSIONS.ANALYTICS_VIEW,
    PERMISSIONS.PROFILE_VIEW,
    PERMISSIONS.PROFILE_EDIT,
  ],
  
  [ROLES.VIEWER]: [
    // Viewers can only see published content
    PERMISSIONS.PORTFOLIO_VIEW,
    PERMISSIONS.PROJECT_VIEW,
    PERMISSIONS.SKILL_VIEW,
    PERMISSIONS.EDUCATION_VIEW,
    PERMISSIONS.SOCIAL_LINK_VIEW,
    PERMISSIONS.DOCUMENT_VIEW,
    PERMISSIONS.VERSION_VIEW,
  ],
  
  [ROLES.AUTHENTICATED]: [
    // Authenticated users can create their own portfolio
    PERMISSIONS.PORTFOLIO_CREATE,
    PERMISSIONS.PORTFOLIO_VIEW,
    PERMISSIONS.PROFILE_VIEW,
    PERMISSIONS.PROFILE_EDIT,
    PERMISSIONS.ANALYTICS_VIEW,
  ],
  
  [ROLES.ANONYMOUS]: [
    // Anonymous users can only view published content
    PERMISSIONS.PORTFOLIO_VIEW,
    PERMISSIONS.PROJECT_VIEW,
    PERMISSIONS.SKILL_VIEW,
    PERMISSIONS.EDUCATION_VIEW,
    PERMISSIONS.SOCIAL_LINK_VIEW,
    PERMISSIONS.DOCUMENT_VIEW,
  ],
};

/**
 * Get permissions for a role
 */
export function getPermissionsForRole(role) {
  return ROLE_PERMISSIONS[role] || [];
}

export default ROLES;
